config/routes.rb
Rails.application.routes.draw do
  get 'chat_rooms/index'
  get 'chat_rooms/show'
  get 'chat_rooms/create'
  devise_for :users
  resources :users, only:[:index, :show]
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
    end
  end

  resources :chat_rooms do 
    resources :direct_messages, only: [:create] 
  end

  resources :chat_rooms, only: [:index, :show, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root :to => 'homes#top'

  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy 
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  validates :name, presence: true

  attachment :profile_image

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
  
  # 相手のユーザーと自分が相互フォローしているか確認するメソッド
  def mutual_follow?(other_user)
    self.following?(other_user) && other_user.following?(self)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(5).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(8).reverse_order
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.following_user.page(params[:page]).per(3).reverse_order
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="row mt-5 w-50">
      <% users.each do |user| %>
      <div class="one-post card mt-3">
        <%= link_to user_path(user) do %>
        <div class="d-flex">
          <%= attachment_image_tag user, :profile_image, size: '50x50', fallback: "no_image.svg", class: "mt-3 profile-img" %>
          <p class="caption h4 mt-4"><%= user.name %></p>
        </div>
        <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= paginate users %>

app/views/users/edit.html.erb
<div class="cover-user-edit">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">プロフィール編集</h1>
    </div>
    <div class="row mt-5">
      <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
        <label class="form-label">名前</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="form-label">プロフィール画像</label><br>
        <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.svg", class: "mb-3 profile-img" %><br>
        <%= f.file_field :profile_image %>
      </div>
      <div class="form-group">
        <label class="form-label">プロフィール</label>
        <%= f.text_field :profile, class: "form-control" %><br>
      </div>
      <%= f.submit '保存する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロワー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロー一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">ユーザ一覧</h1>
    </div>
    <%= render 'index', users: @users, user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<div class="cover-user-show">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <% if user_signed_in? && @user == current_user %>
        <h1 class="font-weight-normal">マイページ</h1>
      <% else %>
        <h1 class="font-weight-normal"><%= @user.name %>さんのページ</h1>
      <% end %>
    </div>
    <% if user_signed_in? && @user == current_user %>
    <p class="d-flex align-self-end">
      <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-success" %>
    </p>
    <% end %>
    <% if current_user != @user %>
      <% if current_user.following?(@user) %>
        <p class="d-flex align-self-end">
          <%= link_to 'フォロー外す', user_relationships_path(@user.id),  data: { turbo_method: :delete }, class: "btn btn-danger" %>
        </p>
        <% else %>
        <p class="d-flex align-self-end">
          <%= link_to 'フォローする', user_relationships_path(@user.id),  data: { turbo_method: :post }, class:"btn btn-success" %>
        </p>
      <% end %>
    <% end %>
    <div class="d-flex w-100">
      <%= attachment_image_tag @user, :profile_image, size: '100x100', fallback: "no_image.svg", class: "mb-3 profile-img" %>
      <h4 class="ml-3 mb-3 card w-100 profile"><%= @user.profile %></h4>
    </div>
    <div class="d-flex">
      <%= link_to follows_user_path(@user) do %>
        <h6>フォロー<%= @following_users.count %></h6>
      <% end %>  
      <%= link_to followers_user_path(@user) do %>
        <h6>フォロワー<%= @follower_users.count %></h6>
      <% end %>
      
      <!-- 相互フォローしている場合のみ、チャットルームリンクを表示 --> 
      <% if current_user.mutual_follow?(@user) %> 
        <%= link_to "チャットルーム", chat_room_path(ChatRoom.find_or_create_by_users(current_user, @user)), class: "btn btn-outline-primary" %> 
      <% else %> 
        <p>相互フォローしていないため、チャットルームにアクセスできません。</p> 
      <% end %> 

    </div>
    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %>
      <div class="one-post col-sm-3 mb-3">
        <%= link_to post_path(post) do %>
          <%= attachment_image_tag post, :image, format: 'jpeg', size: '200x133' %>
          <p class="caption mb-0"><%= post.location %></p>
          <p class="caption"><%= "#{post.comments.count} コメント" %></p>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>