config/routes.rb
Rails.application.routes.draw do
  get 'chat_rooms/index'
  get 'chat_rooms/show'
  get 'chat_rooms/create'
  devise_for :users
  resources :users, only:[:index, :show]
  resources :posts do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    collection do
      get 'confirm'
    end
  end

  resources :chat_rooms do 
    resources :direct_messages, only: [:create] 
  end

  resources :chat_rooms, only: [:index, :show, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root :to => 'homes#top'

  resources :users, only:[:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

end

app/models/post.rb
class Post < ApplicationRecord

    attachment :image
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    validates :location, presence: true, length: { maximum: 15 }
    validates :text, presence: true, length: { maximum: 195 }
    validates :image, presence: true

    enum status: { published: 0, draft: 1 }

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.published.page(params[:page]).reverse_order
    @posts = @posts.where('location LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
  
    # 閲覧数を増やす
    @post.increment!(:view_count)
  
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def confirm
    @posts = current_user.posts.draft.page(params[:page]).reverse_order
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :location, :text, :image, :status)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<div class="row mt-3 mb-3 align-self-end">
  <%= form_with url: posts_path, method: :get, local: true do |f| %>
  <%= f.text_field :search %>
  <%= f.submit '検索する', name: nil %>
  <% end %>
</div>
<div class="row mt-5 index-left w-100">
  <% posts.each do |post| %>
  <div class="one-post col-sm-4 mb-3">
    <%= link_to post_path(post) do %>
    <p class="caption"><%= post.user.name %></p>
    <%= attachment_image_tag post, :image, format: 'jpeg', size: '300x200' %>
    <p class="caption"><%= post.location %></p>
    <p class="caption"><%= "#{post.comments.count} コメント" %></p>
    <% end %>
  </div>
  <% end %>
</div>
<%= paginate posts %>

app/views/posts/confirm.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">下書き一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="cover-edit">
  <div class="container">
    <div class="row">
      <h1 class="font-weight-normal mt-5 mb-5">旅行投稿編集</h1>
    </div>
    <% if @post.errors.any? %>
    <div class="card text-center text-white bg-danger mb-3">
      <%= @post.errors.count %>件のエラーが発生しました
      <% @post.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </div>
    <% end %>
    <div class="row">
      <%= form_with model: @post, local:true do |f| %>
      <div class="form-group mb-3">
        <label class="form-label">旅行先</label>
        <%= f.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group mb-3">
        <label class="form-label">感想</label>
        <%=f.text_area :text, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group mb-4">
        <label class="form-label">画像</label><br>
        <%= f.file_field :image %>
      </div>
      <div class="form-group">
        <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
      <%= f.submit '保存する', class: "btn btn-success" %><br>
      <%= link_to '投稿詳細ページへ', post_path(@post), class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="cover-index"> 
  <div class="container d-flex flex-column align-items-center"> 
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行投稿一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
    </div>
</div>
    <div class="row mt-3 mb-3 align-self-end">
      <%= form_with method: :get, local: true do |f| %>
      <%= f.text_field :search %>
      <%= f.submit '検索する', name: nil %>
      <% end %>
    </div>
    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %> 
        <div class="one-post col-sm-4 mb-3">
          <%= link_to post_path(post) do %> 
            <p class="caption"><%= post.user.name %></p>
            <%= attachment_image_tag post, :image, format: 'jpeg', size: '300x200' %> 
            <p class="caption"><%= post.location %></p> 
            <p class="caption"><%= "#{post.comments.count} コメント" %></p> 
          <% end %> 
        </div> 
      <% end %> 
    </div> 
    <%= paginate @posts %> 
  </div>
</div>

app/views/posts/new.html.erb
<div class="cover-new">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行新規投稿</h1>
    </div>
    <% if @post.errors.any? %>
    <div class="card text-center text-white bg-danger mt-3">
      <%= @post.errors.count %>件のエラーが発生しました
      <% @post.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </div>
    <% end %>
    <div class="row mt-5">
      <%= form_with model: @post, local:true do |f| %>
      <div class="form-group mb-3">
        <label class="form-label">【旅行先】</label>
        <%= f.text_field :location, class: "form-control" %>
      </div>
      <div class="form-group mb-3">
        <label class="form-label">【感想】</label>
        <%=f.text_area :text, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group mb-3">
        <label class="form-label">【画像】</label><br>
        <%= f.file_field :image %>
      </div>
      <div class="form-group">
        <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
      </div>
      <%= f.submit '投稿する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="cover-show">
  <div class="container">
    <div class="row">
      <div class="container d-flex flex-column align-items-center">
        <div class="row mt-5 mb-5">
          <h1 class="font-weight-normal mt-5 mb-5">旅行投稿詳細</h1>
      </div>
      <% if @comment.errors.any? %>
      <div class="card text-center text-white bg-danger mt-3">
        <%= @comment.errors.count %>件のエラーが発生しました
        <% @comment.errors.full_messages.each do |message| %>
         <%= message %>
        <% end %>
      </div>
      <% end %>
      <div class="container d-flex mt-5">
      <div class="d-block">
        <p class="caption"><%= @post.user.name %></p>
        <%= attachment_image_tag @post, :image, format: 'jpeg', size: "450x350" %><br>
        <p class="caption"><%= @post.location %>  
        <% if @post.favorited_by?(current_user) %>
          <%= link_to post_favorites_path(@post),  data: { turbo_method: :delete }, class: "favorite_btn" do %>
          ♥<%= @post.favorites.count %> いいね
          <% end %>
          <% else %>
          <%= link_to post_favorites_path(@post),  data: { turbo_method: :post }, class: "favorite_btn" do %>
            ♡<%= @post.favorites.count %> いいね
          <% end %>
          <% end %>
        </p>
        閲覧数: <%= @post.view_count %>
        <h2>感想</h2>
        <p id="text"><%= @post.text %></p>
    <% if @post.user == current_user %>
        <%= link_to '編集する', edit_post_path(@post.id), class: "btn btn-info mr-3" %>
        <%= link_to '削除する', post_path(@post.id),  data: { turbo_method: :delete, turbo_confirm:  "本当に消しますか？"}, class: "btn btn-danger" %><br>
    <% end %>
        <%= link_to '投稿一覧ページへ', posts_path, class: "btn btn-dark mt-3" %>
    </div>
    <div class="comments ml-5 mt-5">
        <%= form_with(model:[@post, @comment], local: true) do |f| %>
        <%= f.text_area :comment, :size=>"60x3",placeholder: "コメントする" %>
        <%= f.submit "送信する", class: "btn btn-success mb-4" %>
        <% end %>

        <p>コメント件数：<%= @comments.count %></p>
          <% @comments.each do |comment| %>
        <div class="comments-index mb-2">
          <%= comment.user.name %>
          <%= comment.created_at.strftime('%Y/%m/%d') %><br>
          <div class="d-flex">
            <%= comment.comment %>
            <% if comment.user == current_user %>
            <div class="comment-delete">
              <%= link_to "削除", post_comment_path(comment.post, comment),  data: { turbo_method: :delete }, class: "btn-sm btn-danger" %>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
        <%= paginate @comments %>
      </div>
    </div>
  </div>
</div>